config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index] do
    resources :countries, except: [:new, :edit] do
      resources :blogs
    end
  end


  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :country
  validates :country, presence: true
  validates :title, presence: true
  validates :post, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blogs
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET countries/1/blogs
  def index
    @blogs = @country.blogs
  end

  # GET countries/1/blogs/1
  def show
  end

  # GET countries/1/blogs/new
  def new
    @blog = @country.blogs.build
  end

  # GET countries/1/blogs/1/edit
  def edit
  end

  # POST countries/1/blogs
  def create
    @blog = @country.blogs.build(blog_params)
    if @blog.save
      redirect_to([@country.user, @country], notice: 'Blog was successfully posted.')
    end
  end

  # PUT countries/1/blogs/1
  # def update
  #   if @blog.update_attributes(blog_params)
  #     redirect_to([@blog.country, @blog], notice: 'Blog was successfully updated.')
  #   else
  #     render action: 'edit'
  #   end
  # end

  # DELETE countries/1/blogs/1
  def destroy
    @blog.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogs
      @country = Country.find(params[:country_id])
    end

    def set_blog
      @blog = @country.blogs.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_params
      params.require(:blog).permit(:title, :post)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog, as: :blog, url: user_country_blog_path(@blog), method: :post do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_area :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', [@blog.country, @blog] %> |
<%= link_to 'Back', country_blogs_path(@blog.country) %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.post %></td>
  </tr>
<% end %>
</table>

<br />

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', country_blogs_path(@blog.country) %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Post:</b>
  <%= @blog.post %>
</p>


<%= link_to 'Edit', edit_country_blog_path(@blog.country, @blog) %> |
<%= link_to 'Back', country_blogs_path(@blog.country) %>